services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mouad
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo

  bns-api:
    container_name: bns-api
    image: bsn/bns:1.0.3
    depends_on:
      - postgres
    ports:
      - 8088:8088
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-sql-bsn:5432/book_social_network
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mouad
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - spring-demo
  bns-ui:
    container_name: bns-ui
    image: bsn/bns-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - bns-api


  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local
