name: BSN Backend API Pipeline (Local Runner)

on:
  push:
    branches:
      - branch-Docker
    paths:
      - book-network/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml

jobs:

  compile:
    runs-on: self-hosted
    name: Compile Project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Compile
        run: |
          cd book-network
          ./mvnw clean compile


  unit-tests:
    runs-on: self-hosted
    needs: compile
    name: Unit Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Run Tests
        run: |
          cd book-network
          ./mvnw clean test


  build:
    runs-on: self-hosted
    needs: [unit-tests]
    name: Build JAR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Package
        run: |
          cd book-network
          ./mvnw clean package


  build-image:
    runs-on: self-hosted
    needs: build
    name: Build Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Maven Version
        id: extract_version
        run: |
          cd book-network
          echo "VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bsn-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bsn-api:${{ steps.extract_version.outputs.VERSION }}
          build-args: |
            PROFILE=dev
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
